### ISSUE TITLE
Cool bot but idk why i have errors

### ISSUE THREAD

**Issue by LosBagros** [anoadragon453/discord-voice-channel-kick-bot#1]
`Connected and logged in. Here I come!
Trigger phrase ACTIVATED! Waiting 0 seconds...
Triggered!
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Los_Bagros\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Code\test\discord-voice-channel-kick-bot\main.py", line 167, in on_message
    await start_a_tour()
  File "D:\Code\test\discord-voice-channel-kick-bot\main.py", line 25, in start_a_tour
    voice_client: discord.VoiceClient = await voice_channel.connect()
AttributeError: 'NoneType' object has no attribute 'connect'
`

**Comment by LosBagros** [comment]
Pls help

**Comment by anoadragon453** [comment]
Ah, yeah. The `discord.py` library had a backwards-incompatible change, which I believe I fixed on the [ucmb branch](https://github.com/anoadragon453/discord-voice-channel-kick-bot/tree/ucmb), but haven't ported to `master` yet.

To be honest I don't maintain this repository anymore (it was just a fun bot for use with friends), but feel free to submit a PR fixing it up!
